#!/bin/sh
# Run the Docker integration test suite.
#
# Usage:
#   ./tests/run-docker-tests.sh              # Full test suite
#   ./tests/run-docker-tests.sh --no-build   # Skip image build
#   ./tests/run-docker-tests.sh --validate   # Config validation only (no Docker)

set -e

cd "$(dirname "$0")/.."

if [ "$1" = "--validate" ]; then
  echo "Running config validation (no Docker required)..."
  echo ""
  # Generate a test config to a temp file and validate it
  TMPDIR=$(mktemp -d)
  trap "rm -rf $TMPDIR" EXIT

  # Create a minimal dovecot.conf from the template for validation
  cat > "$TMPDIR/dovecot.conf" << 'TESTCONF'
dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0
# Generated by mailserver test
protocols = imap pop3 lmtp
hostname = mail.test.local

mail_driver = maildir
mail_home = /data/mail/%{user | domain}/%{user | username}
mail_path = Maildir

ssl = yes
ssl_server_cert_file = /data/ssl/cert.pem
ssl_server_key_file = /data/ssl/key.pem
ssl_server_dh_file = /usr/share/dovecot/dh.pem

passdb passwd-file {
  passdb_passwd_file = /etc/dovecot/passwd
}

userdb static {
  userdb_uid = vmail
  userdb_gid = vmail
  userdb_home = /data/mail/%{user | domain}/%{user | username}
}

auth_username_format = %u
log_path = /dev/stdout
auth_mechanisms = plain login
TESTCONF

  exec ./tests/validate-dovecot-config.sh "$TMPDIR/dovecot.conf"
fi

# Docker test suite
BUILD_FLAG=""
if [ "$1" = "--no-build" ]; then
  BUILD_FLAG="--no-build"
fi

echo "Building and starting test services..."
docker compose -f docker-compose.test.yml up --build $BUILD_FLAG \
  --abort-on-container-exit --exit-code-from test 2>&1

EXIT_CODE=$?

echo ""
echo "Tearing down test services..."
docker compose -f docker-compose.test.yml down -v 2>/dev/null

exit $EXIT_CODE
